# Generated by Django 2.2.2 on 2019-07-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sems', models.CharField(max_length=100)),
                ('link2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop.branch')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=100)),
                ('link3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop.sem')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='link1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drop.course'),
        ),
    ]
