# Generated by Django 2.2.2 on 2019-07-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='section',
        ),
    ]
